version: '3.8'

services:
  # ----------------------------------------
  # 1. Jenkins Service
  # ----------------------------------------
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-local
    user: root # Required to access the docker socket on host
    privileged: true
    ports:
      - "8081:8080" # We map Jenkins to 8081 to avoid conflict with your App (8080)
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Allow Jenkins to use Docker
    networks:
      - ci-network
    depends_on:
      - sonarqube

  # ----------------------------------------
  # 2. SonarQube Service (We'll run it here too!)
  # ----------------------------------------
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-local
    ports:
      - "9000:9000"
    networks:
      - ci-network
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

volumes:
  jenkins_data:

networks:
  ci-network: